## NUMPY ( numerical Python)

## 1. Create array

In [1]:
import numpy as np

In [2]:
## 1D array
a1=np.array([4,5,6,7,9])

In [3]:
a1

array([4, 5, 6, 7, 9])

In [4]:
## 2d 
a2=np.array([[3,4,5],[6,7,8]])
a2
## 3d 

array([[3, 4, 5],
       [6, 7, 8]])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.random.rand(50)

array([0.59968835, 0.50943576, 0.10549069, 0.69460254, 0.03192112,
       0.91173974, 0.44359555, 0.02515249, 0.14499389, 0.57024015,
       0.57861642, 0.51938206, 0.2472595 , 0.33605762, 0.59803459,
       0.21458056, 0.41982956, 0.26752186, 0.60457714, 0.22494663,
       0.95439074, 0.04430492, 0.87987551, 0.4619955 , 0.90928148,
       0.68910192, 0.16241756, 0.31861273, 0.1209185 , 0.06140323,
       0.66794524, 0.58381812, 0.47520611, 0.91553552, 0.25430828,
       0.89300567, 0.97178433, 0.33044314, 0.32750096, 0.22415561,
       0.71521054, 0.3901484 , 0.13898509, 0.02952986, 0.73381673,
       0.91232027, 0.28705827, 0.13495676, 0.72260965, 0.08000839])

In [16]:
np.random.seed(42)
np.random.randint(0,50,100)

array([38, 28, 14, 42,  7, 20, 38, 18, 22, 10, 10, 23, 35, 39, 23,  2, 21,
        1, 23, 43, 29, 37,  1, 20, 32, 11, 21, 43, 24, 48, 26, 41, 27, 15,
       14, 46, 43,  2, 36,  6, 20,  8, 38, 17,  3, 24, 13, 49,  8, 25,  1,
       19, 27, 46,  6, 43,  7, 46, 34, 13, 16, 35, 49, 39,  3,  1,  5, 41,
        3, 28, 17, 25, 43, 33,  9, 35, 13, 30, 47, 14,  7, 13, 22, 39, 20,
       15, 44, 17, 46, 23, 25, 24, 44, 40, 28, 14, 44,  0, 24,  6],
      dtype=int32)

### 2. Array attributes

In [17]:
a=np.array([3,4,5])

In [18]:
a.dtype

dtype('int64')

In [19]:
a=a.astype('int32')

In [20]:
a.dtype

dtype('int32')

In [21]:
b=np.array([1,2,'a'])

In [22]:
b.dtype

dtype('<U21')

In [23]:
a.ndim

1

In [24]:
c=np.array([[2,3,4],[5,6,8]])

In [25]:
c.ndim

2

In [26]:
a.shape

(3,)

In [27]:
b.shape

(3,)

In [28]:
c.shape

(2, 3)

In [29]:
a.size

3

In [30]:
b.size

3

In [31]:
c.size

6

In [32]:
e=np.array(['a','b','c','d','e'])

In [33]:
m,n=np.unique(e,return_index=True)

In [34]:
m

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [35]:
n

array([0, 1, 2, 3, 4])

### 3. Array operations

In [36]:
x=np.array([4,5,6])

In [37]:
## 1. arithemetic ops
x+2

array([6, 7, 8])

In [38]:
x-2

array([2, 3, 4])

In [39]:
x*3

array([12, 15, 18])

In [40]:
## 2.function ops
np.sum(x)

np.int64(15)

In [41]:
np.mean(x)

np.float64(5.0)

In [42]:
z=np.array([3,4,5])

In [43]:
z.ndim

1

In [44]:
y=np.array([[2],[3],[5]])

In [45]:
y.ndim

2

In [46]:
np.median(a)

np.float64(4.0)

In [47]:
from scipy import stats

In [48]:
stats.mode(a)

ModeResult(mode=np.int32(3), count=np.int64(1))

In [49]:
a.mean()

np.float64(4.0)

In [50]:
np.mean(a)

np.float64(4.0)

In [51]:
np.std(a)

np.float64(0.816496580927726)

In [52]:
a.std()

np.float64(0.816496580927726)

In [53]:
np.var(a)

np.float64(0.6666666666666666)

In [54]:
a.var()

np.float64(0.6666666666666666)

In [55]:
## column wise and row wise operations
m=np.array([[2,3,4],[5,6,7],[7,8,4]])

In [56]:
m

array([[2, 3, 4],
       [5, 6, 7],
       [7, 8, 4]])

In [57]:
## columns wise
## axis=0 (columns)
## axis=1 (rows)

In [58]:
m.sum(axis=0)

array([14, 17, 15])

In [59]:
m.sum(axis=1)

array([ 9, 18, 19])

In [60]:
## array broadcasting
print(m) ## (3,3)
m.shape

[[2 3 4]
 [5 6 7]
 [7 8 4]]


(3, 3)

In [61]:
n=np.array([3,5,6])  ##(3,)
n.shape

(3,)

In [62]:
n

array([3, 5, 6])

In [63]:
m+n

array([[ 5,  8, 10],
       [ 8, 11, 13],
       [10, 13, 10]])

In [64]:
m

array([[2, 3, 4],
       [5, 6, 7],
       [7, 8, 4]])

In [65]:
w=np.array([[1,2,3],[6,7,8],[9,0,5]])

In [66]:
w

array([[1, 2, 3],
       [6, 7, 8],
       [9, 0, 5]])

In [67]:
m.dot(w)

array([[ 56,  25,  50],
       [104,  52,  98],
       [ 91,  70, 105]])

In [68]:
np.dot(m,w)

array([[ 56,  25,  50],
       [104,  52,  98],
       [ 91,  70, 105]])

In [69]:
m@w

array([[ 56,  25,  50],
       [104,  52,  98],
       [ 91,  70, 105]])

In [70]:
np.cross(m,w)

array([[  1,  -2,   1],
       [ -1,   2,  -1],
       [ 40,   1, -72]])

In [71]:
np.linalg.inv(m)

array([[-2.13333333,  1.33333333, -0.2       ],
       [ 1.93333333, -1.33333333,  0.4       ],
       [-0.13333333,  0.33333333, -0.2       ]])

## 4.NumPy Copy vs View, Shape Manipulation, and Reshaping Arrays

In [72]:
l=[2,3,4,5,6,7]

In [73]:
x=l[2:5]

In [74]:
l

[2, 3, 4, 5, 6, 7]

In [75]:
x

[4, 5, 6]

In [76]:
l[3]=45

In [77]:
x

[4, 5, 6]

In [78]:
l

[2, 3, 4, 45, 6, 7]

In [79]:
l

[2, 3, 4, 45, 6, 7]

In [80]:
x=l.copy()

In [81]:
z=np.arange(1,13)

In [82]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [83]:
z.reshape(3,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 5.NumPy Array Iteration, Joining, and Splitting

In [84]:
a1=np.array([1,2,3,5])
a2=np.array([[2,3,4],[5,6,7],[9,8,1]])
a3=np.array([[[1,2,3],[5,6,7],[6,7,7]]])

In [85]:
a3.ndim

3

In [86]:
for i in a1:
    print(i,end=" ")

1 2 3 5 

In [87]:
a2

array([[2, 3, 4],
       [5, 6, 7],
       [9, 8, 1]])

In [88]:
for i in a2:
    for j in i:
        print(j,end=" ")

2 3 4 5 6 7 9 8 1 

In [89]:
for i in a3:
    for j in i:
        for k in j:
            print(k,end=" ")

1 2 3 5 6 7 6 7 7 

In [90]:
for i in np.nditer(a3):
    print(i,end=" ")

1 2 3 5 6 7 6 7 7 

### 6. NumPy Searching, Sorting, and Filtering

In [91]:
a1

array([1, 2, 3, 5])

In [92]:
## searching
indices=np.where(a1>2)

In [93]:
indices

(array([2, 3]),)

In [94]:
b=np.array([10,3,5,90,56,23])

In [95]:
## sorting
np.sort(b)

array([ 3,  5, 10, 23, 56, 90])

In [96]:
b.sort()

In [97]:
b

array([ 3,  5, 10, 23, 56, 90])

In [98]:
c=np.array([5,34,21,9,4])

In [99]:
c

array([ 5, 34, 21,  9,  4])

In [100]:
np.extract(c>10,c)

array([34, 21])

In [101]:
l1=np.array([5,6,7])
l2=np.array([4,3,2])
l3=np.array([9,0,3])

In [102]:
np.stack((l1,l2,l3))

array([[5, 6, 7],
       [4, 3, 2],
       [9, 0, 3]])

In [103]:
x1=np.hstack((l1,l2,l3))

In [104]:
x2=np.vstack((l1,l2,l3))  ## np.stack=np.vstack

In [105]:
x3=np.dstack((l1,l2,l3))

In [106]:
print(x1)
print(x2)
print(x3)

[5 6 7 4 3 2 9 0 3]
[[5 6 7]
 [4 3 2]
 [9 0 3]]
[[[5 4 9]
  [6 3 0]
  [7 2 3]]]


In [107]:
np.split(x1,3)

[array([5, 6, 7]), array([4, 3, 2]), array([9, 0, 3])]

In [108]:
np.vsplit(x2,3)

[array([[5, 6, 7]]), array([[4, 3, 2]]), array([[9, 0, 3]])]

In [109]:
np.hsplit(x1,3)  ## np.split=np.hsplit

[array([5, 6, 7]), array([4, 3, 2]), array([9, 0, 3])]

In [110]:
np.dsplit(x3,3)

[array([[[5],
         [6],
         [7]]]),
 array([[[4],
         [3],
         [2]]]),
 array([[[9],
         [0],
         [3]]])]

In [111]:
import numpy as np
from datetime import datetime

In [112]:
x5 = np.array([
    datetime(2020,3,12),
    datetime(2021,4,13),
    datetime(2022,5,15),
    datetime(2023,6,18),
    datetime(2025,9,23)
])

In [113]:
from datetime import date



In [114]:
a=np.array([np.datetime64(date(2025,11,12))])

In [115]:
a.dtype

dtype('<M8[D]')

In [116]:
a.astype('int64')

array([20404])