## NUMPY ( numerical Python)

## 1. Create array

In [14]:
import numpy as np

In [15]:
l1=[2,3,5]
l2=[5,6,9]

In [16]:
l1+l2

[2, 3, 5, 5, 6, 9]

In [17]:
l1-l2

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [ ]:
! pip install numpy

In [ ]:
import numpy as np

In [ ]:
a1=np.array(l1)
a2=np.array(l2)

In [ ]:
a1+a2

array([ 7,  9, 14])

In [ ]:
a1-a2

array([-3, -3, -4])

In [ ]:
## 1D array
a1=np.array([4,5,6,7,9])

In [ ]:
a1

array([4, 5, 6, 7, 9])

In [ ]:
## 2d 
a2=np.array([[3,4,5],[6,7,8]])
a2
## 3d
a3=np.array([[[2,3,5],[5,4,2]],[[6,7,8],[3,1,2]]]) 

In [ ]:
a3

array([[[2, 3, 5],
        [5, 4, 2]],

       [[6, 7, 8],
        [3, 1, 2]]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.array(list(range(0,10,2)))

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [ ]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

# NumPy Random Module Cheat Sheet

---

# 1. Core Sampling Methods

```python
rng = np.random.default_rng()
```

| Method | Description |
|--------|-------------|
| `rng.random(size=None)` | Returns random floats uniformly in the interval `[0.0, 1.0)` |
| `rng.integers(low, high=None, size=None, endpoint=False)` | Returns random integers from `low` (inclusive) to `high` (exclusive/inclusive depending on `endpoint`) |
| `rng.choice(a, size=None, replace=True, p=None, axis=0)` | Random sample from a 1D array or integer range |
| `rng.bytes(length)` | Returns a random string of bytes |

---

# 2. Permutations and Shuffling

| Method | Description |
|--------|-------------|
| `rng.shuffle(x, axis=0)` | Shuffles an array **in-place** |
| `rng.permutation(x, axis=0)` | Returns a randomly permuted copy |
| `rng.permuted(x, axis=None)` | Permutes elements independently along an axis |

---

# 3. Statistical Distributions

> **All distribution methods accept a `size` parameter.**

| Method | Description |
|--------|-------------|
| `rng.standard_normal(size=None)` | Standard Normal distribution (μ=0, σ=1) |
| `rng.normal(loc=0.0, scale=1.0, size=None)` | Normal (Gaussian) distribution |
| `rng.uniform(low=0.0, high=1.0, size=None)` | Uniform distribution |
| `rng.binomial(n, p, size=None)` | Binomial distribution |
| `rng.poisson(lam=1.0, size=None)` | Poisson distribution |
| `rng.exponential(scale=1.0, size=None)` | Exponential distribution |
| `rng.beta(a, b, size=None)` | Beta distribution |
| `rng.gamma(shape, scale=1.0, size=None)` | Gamma distribution |
| `rng.chisquare(df, size=None)` | Chi-square distribution |
| `rng.standard_t(df, size=None)` | Student's t distribution |
| `rng.f(dfnum, dfden, size=None)` | F (Fisher-Snedecor) distribution |
| `rng.logistic(loc=0.0, scale=1.0, size=None)` | Logistic distribution |
| `rng.lognormal(mean=0.0, sigma=1.0, size=None)` | Log-normal distribution |
| `rng.multinomial(n, pvals, size=None)` | Multinomial distribution |
| `rng.multivariate_normal(mean, cov, size=None)` | Multivariate Normal distribution |
| `rng.dirichlet(alpha, size=None)` | Dirichlet distribution |
| `rng.geometric(p, size=None)` | Geometric distribution |
| `rng.gumbel(loc=0.0, scale=1.0, size=None)` | Gumbel distribution |
| `rng.hypergeometric(ngood, nbad, nsample, size=None)` | Hypergeometric distribution |
| `rng.laplace(loc=0.0, scale=1.0, size=None)` | Laplace (Double Exponential) distribution |
| `rng.logseries(p, size=None)` | Logarithmic Series distribution |
| `rng.negative_binomial(n, p, size=None)` | Negative Binomial distribution |
| `rng.noncentral_chisquare(df, nonc, size=None)` | Non-central Chi-square distribution |
| `rng.noncentral_f(dfnum, dfden, nonc, size=None)` | Non-central F distribution |
| `rng.pareto(a, size=None)` | Pareto distribution |
| `rng.power(a, size=None)` | Power distribution |
| `rng.rayleigh(scale=1.0, size=None)` | Rayleigh distribution |
| `rng.standard_cauchy(size=None)` | Standard Cauchy distribution |
| `rng.standard_exponential(size=None)` | Standard Exponential distribution |
| `rng.standard_gamma(shape, size=None)` | Standard Gamma distribution |
| `rng.triangular(left, mode, right, size=None)` | Triangular distribution |
| `rng.vonmises(mu, kappa, size=None)` | Von Mises distribution |
| `rng.wald(mean, scale, size=None)` | Wald (Inverse Gaussian) distribution |
| `rng.weibull(a, size=None)` | Weibull distribution |
| `rng.zipf(a, size=None)` | Zipf distribution |

---

# 4. Legacy API (`np.random.*`)

> ⚠️ These functions use the older **Mersenne Twister** generator.
>
> **Use `default_rng()` for new code.**

---

## Simple Random Data Functions

| Method | Description |
|--------|-------------|
| `np.random.rand(d0, d1, ..., dn)` | Uniform floats in `[0,1)` |
| `np.random.randn(d0, d1, ..., dn)` | Standard Normal distribution |
| `np.random.randint(low, high=None, size=None)` | Random integers |
| `np.random.random_sample(size=None)` | Uniform floats |
| `np.random.random(size=None)` | Alias of `random_sample()` |
| `np.random.ranf(size=None)` | Alias of `random_sample()` |
| `np.random.sample(size=None)` | Alias of `random_sample()` |
| `np.random.choice(a, size=None, replace=True, p=None)` | Random selection |
| `np.random.bytes(length)` | Random bytes |

---

## Shuffling and Seeding

| Method | Description |
|--------|-------------|
| `np.random.shuffle(x)` | Shuffle array in-place |
| `np.random.permutation(x)` | Return shuffled copy |
| `np.random.seed(seed=None)` | Set global random seed |
| `np.random.get_state()` | Get generator state |
| `np.random.set_state()` | Restore generator state |

---

## Distribution Functions

The legacy API provides the same distribution names:

```python
np.random.normal()
np.random.uniform()
np.random.binomial()
np.random.poisson()
np.random.exponential()
...
```

---

# 5. Helper & Bit Generator Infrastructure

| Method | Description |
|--------|-------------|
| `np.random.default_rng()` | Creates the recommended Generator |
| `np.random.RandomState()` | Legacy random generator |
| `np.random.PCG64` | High-quality bit generator |
| `np.random.PCG64DXSM` | Improved PCG64 variant |
| `np.random.MT19937` | Mersenne Twister bit generator |
| `np.random.Philox` | Counter-based generator |
| `np.random.SFC64` | Fast Small Counter generator |
| `np.random.SeedSequence` | Advanced seed management |

---

# Recommendation

✅ **Use this in new code**

```python
import numpy as np

rng = np.random.default_rng(42)

numbers = rng.normal(size=10)
```

Avoid:

```python
np.random.seed(42)
np.random.normal(size=10)
```

unless you're maintaining legacy code.

In [ ]:
np.random.rand()

array([[[0.04607016, 0.20307791, 0.16334724, 0.69469462],
        [0.59666836, 0.04799795, 0.57118652, 0.61637507],
        [0.64529379, 0.41876426, 0.42030796, 0.76812842]],

       [[0.26057488, 0.51638158, 0.64807899, 0.7042963 ],
        [0.54977979, 0.66272804, 0.14572749, 0.60609483],
        [0.81167818, 0.95992719, 0.015931  , 0.93987212]],

       [[0.00489945, 0.15494872, 0.07033451, 0.27304161],
        [0.8705801 , 0.48819165, 0.01621869, 0.19794076],
        [0.76316532, 0.37494117, 0.09202832, 0.44835988]],

       [[0.85981382, 0.35373171, 0.00120749, 0.28708992],
        [0.60488609, 0.05875864, 0.23501791, 0.41823447],
        [0.11540543, 0.40130625, 0.07262606, 0.52800591]]])

In [ ]:
np.random.seed(42)
np.random.randint(1,50,100)

array([39, 29, 15, 43,  8, 21, 39, 19, 23, 11, 11, 24, 36, 40, 24,  3, 22,
        2, 24, 44, 30, 38,  2, 21, 33, 12, 22, 44, 25, 49, 27, 42, 28, 16,
       15, 47, 44,  3, 37,  7, 21,  9, 39, 18,  4, 25, 14,  9, 26,  2, 20,
       28, 47,  7, 44,  8, 47, 35, 14, 17, 36, 40,  4,  2,  6, 42,  4, 29,
       18, 26, 44, 34, 10, 36, 14, 31, 48, 15,  8, 14, 23, 40, 21, 16, 45,
       18, 47, 24, 26, 25, 45, 41, 29, 15, 45,  1, 25,  7,  9, 24],
      dtype=int32)

In [ ]:
np.random.seed(42)
np.random.randint(0,50,100)

array([38, 28, 14, 42,  7, 20, 38, 18, 22, 10, 10, 23, 35, 39, 23,  2, 21,
        1, 23, 43, 29, 37,  1, 20, 32, 11, 21, 43, 24, 48, 26, 41, 27, 15,
       14, 46, 43,  2, 36,  6, 20,  8, 38, 17,  3, 24, 13, 49,  8, 25,  1,
       19, 27, 46,  6, 43,  7, 46, 34, 13, 16, 35, 49, 39,  3,  1,  5, 41,
        3, 28, 17, 25, 43, 33,  9, 35, 13, 30, 47, 14,  7, 13, 22, 39, 20,
       15, 44, 17, 46, 23, 25, 24, 44, 40, 28, 14, 44,  0, 24,  6],
      dtype=int32)

### 2. Array attributes

In [ ]:
a=np.array([3,4,5])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a=a.astype('float')

In [ ]:
a.dtype

dtype('float64')

In [ ]:
b=np.array([1,2,'a'])

In [ ]:
b.dtype

dtype('<U21')

In [ ]:
a.ndim

1

In [ ]:
c=np.array([[[2,3,4],[5,6,8]],[[8,2,3],[5,6,7]]])

In [ ]:
c.ndim

3

In [ ]:
c.shape

(2, 2, 3)

In [ ]:
c.size

12

In [ ]:
b.shape

(3,)

In [ ]:
c.shape

(2, 2, 3)

In [ ]:
a.size

3

In [ ]:
b.size

3

In [ ]:
c.size

12

In [ ]:
e=np.array(['a','b','c','d','e'])

In [ ]:
m,n=np.unique(e,return_index=True)

In [ ]:
m

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [ ]:
n

array([0, 1, 2, 3, 4])

### 3. Array operations

In [ ]:
x=np.array([4,5,6])

In [ ]:
## 1. arithemetic ops
x+2

array([6, 7, 8])

In [ ]:
x-2

array([2, 3, 4])

In [ ]:
x*3

array([12, 15, 18])

In [ ]:
## 2.function ops
np.sum(x)

np.int64(15)

In [ ]:
np.mean(x)

np.float64(5.0)

In [ ]:
z=np.array([3,4,5])

In [ ]:
z.ndim

1

In [ ]:
y=np.array([[2],[3],[5]])

In [ ]:
y.ndim

2

In [ ]:
np.median(a)

np.float64(4.0)

In [ ]:
from scipy import stats

In [ ]:
stats.mode(a)

ModeResult(mode=np.int32(3), count=np.int64(1))

In [ ]:
a.mean()

np.float64(4.0)

In [ ]:
np.mean(a)

np.float64(4.0)

In [ ]:
np.std(a)

np.float64(0.816496580927726)

In [ ]:
a.std()

np.float64(0.816496580927726)

In [ ]:
np.var(a)

np.float64(0.6666666666666666)

In [ ]:
a.var()

np.float64(0.6666666666666666)

In [ ]:
## column wise and row wise operations
m=np.array([[2,3,4],[5,6,7],[7,8,4]])

In [ ]:
m

array([[2, 3, 4],
       [5, 6, 7],
       [7, 8, 4]])

In [ ]:
## columns wise
## axis=0 (column)
## axis=1 (rows)

In [ ]:
m.sum(axis=0)

array([14, 17, 15])

In [ ]:
m.sum(axis=1)

array([ 9, 18, 19])

In [ ]:
## array broadcasting
m=np.array([[2,3,4],[5,6,7],[7,8,4]])

In [ ]:
m.ndim

2

In [ ]:
n=np.array([3,5,6])

In [ ]:
n.ndim

1

In [ ]:
print(m)
print(n)

[[2 3 4]
 [5 6 7]
 [7 8 4]]
[3 5 6]


In [ ]:
m+n

array([[ 5,  8, 10],
       [ 8, 11, 13],
       [10, 13, 10]])

In [ ]:
m

array([[2, 3, 4],
       [5, 6, 7],
       [7, 8, 4]])

In [ ]:
w=np.array([[1,2,3],[6,7,8],[9,0,5]])

In [ ]:
w

array([[1, 2, 3],
       [6, 7, 8],
       [9, 0, 5]])

In [ ]:
m.dot(w)

array([[ 56,  25,  50],
       [104,  52,  98],
       [ 91,  70, 105]])

In [ ]:
np.dot(m,w)

array([[ 56,  25,  50],
       [104,  52,  98],
       [ 91,  70, 105]])

In [ ]:
m@w

array([[ 56,  25,  50],
       [104,  52,  98],
       [ 91,  70, 105]])

In [ ]:
np.cross(m,w)

array([[  1,  -2,   1],
       [ -1,   2,  -1],
       [ 40,   1, -72]])

In [ ]:
np.linalg.inv(m)

array([[-2.13333333,  1.33333333, -0.2       ],
       [ 1.93333333, -1.33333333,  0.4       ],
       [-0.13333333,  0.33333333, -0.2       ]])

## 4.NumPy Copy vs View, Shape Manipulation, and Reshaping Arrays

In [ ]:
l=[2,3,4,5,6,7]

In [ ]:
x=l[2:5]

In [ ]:
l

[2, 3, 4, 5, 6, 7]

In [ ]:
x

[4, 5, 6]

In [ ]:
l[3]=45

In [ ]:
x

[4, 5, 6]

In [ ]:
l

[2, 3, 4, 45, 6, 7]

In [ ]:
l

[2, 3, 4, 45, 6, 7]

In [ ]:
x=l.copy()

In [ ]:
l

[2, 3, 4, 45, 6, 7]

In [ ]:
x

[2, 3, 4, 45, 6, 7]

In [ ]:
x[3]=60

In [ ]:
x

[2, 3, 4, 60, 6, 7]

In [ ]:
l

[2, 3, 4, 45, 6, 7]

In [ ]:
z=np.arange(1,13)

In [ ]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
z.reshape(3,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 5.NumPy Array Iteration, Joining, and Splitting

In [ ]:
a1=np.array([1,2,3,5])
a2=np.array([[2,3,4],[5,6,7],[9,8,1]])
a3=np.array([[[1,2,3],[5,6,7],[6,7,7]]])

In [ ]:
a3.ndim

3

In [ ]:
for i in a1:
    print(i,end=" ")

1 2 3 5 

In [ ]:
a2

array([[2, 3, 4],
       [5, 6, 7],
       [9, 8, 1]])

In [ ]:
for i in a2:
    for j in i:
        print(j,end=" ")

2 3 4 5 6 7 9 8 1 

In [ ]:
for i in a3:
    for j in i:
        for k in j:
            print(k,end=" ")

1 2 3 5 6 7 6 7 7 

In [ ]:
for i in np.nditer(a3):
    print(i,end=" ")

1 2 3 5 6 7 6 7 7 

### 6. NumPy Searching, Sorting, and Filtering

In [ ]:
a1=np.array([3,4,2,1,7])

In [ ]:
## searching
indices=np.where(a1>2)

In [ ]:
indices

(array([0, 1, 4]),)

In [ ]:
np.extract(a1>2,a1)

array([3, 4, 7])

In [ ]:
b=np.array([10,3,5,90,56,23])

In [ ]:
## sorting
np.sort(b)

array([ 3,  5, 10, 23, 56, 90])

In [ ]:
b.sort()

In [ ]:
b

array([ 3,  5, 10, 23, 56, 90])

In [ ]:
c=np.array([5,34,21,9,4])

In [ ]:
c

array([ 5, 34, 21,  9,  4])

In [ ]:
np.extract(c>10,c)

array([34, 21])

In [19]:
l1=np.array([5,6,7])
l2=np.array([4,3,2])
l3=np.array([9,0,3])

In [20]:
np.stack((l1,l2,l3))

array([[5, 6, 7],
       [4, 3, 2],
       [9, 0, 3]])

In [21]:
x1=np.hstack((l1,l2,l3))

In [22]:
x1

array([5, 6, 7, 4, 3, 2, 9, 0, 3])

In [23]:
x2=np.vstack((l1,l2,l3))  ## np.stack=np.vstack

In [24]:
x2

array([[5, 6, 7],
       [4, 3, 2],
       [9, 0, 3]])

In [28]:
x2.ndim

2

In [25]:
x3=np.dstack((l1,l2,l3))

In [26]:
x3

array([[[5, 4, 9],
        [6, 3, 0],
        [7, 2, 3]]])

In [27]:
x3.ndim

3

In [ ]:
print(x1)
print(x2)
print(x3)

[5 6 7 4 3 2 9 0 3]
[[5 6 7]
 [4 3 2]
 [9 0 3]]
[[[5 4 9]
  [6 3 0]
  [7 2 3]]]


In [35]:
print(x1)
print(x1.ndim)

[5 6 7 4 3 2 9 0 3]
1


In [36]:
np.split(x1,3)

[array([5, 6, 7]), array([4, 3, 2]), array([9, 0, 3])]

In [37]:
np.hsplit(x1,3)

[array([5, 6, 7]), array([4, 3, 2]), array([9, 0, 3])]

In [41]:
print(x2)
x2.ndim


[[5 6 7]
 [4 3 2]
 [9 0 3]]


2

In [43]:
np.vsplit(x2,3)

[array([[5, 6, 7]]), array([[4, 3, 2]]), array([[9, 0, 3]])]

In [ ]:
np.hsplit(x1,3)  ## np.split=np.hsplit

[array([5, 6, 7]), array([4, 3, 2]), array([9, 0, 3])]

In [44]:
np.dsplit(x3,3)

[array([[[5],
         [6],
         [7]]]),
 array([[[4],
         [3],
         [2]]]),
 array([[[9],
         [0],
         [3]]])]

In [46]:
from datetime import datetime

In [47]:
order_date = np.array([
    datetime(2020,3,12),
    datetime(2021,4,13),
    datetime(2022,5,15),
    datetime(2023,6,18),
    datetime(2025,9,23)
])

In [48]:
order_date

array([datetime.datetime(2020, 3, 12, 0, 0),
       datetime.datetime(2021, 4, 13, 0, 0),
       datetime.datetime(2022, 5, 15, 0, 0),
       datetime.datetime(2023, 6, 18, 0, 0),
       datetime.datetime(2025, 9, 23, 0, 0)], dtype=object)

In [49]:
order_date.dtype

dtype('O')

In [ ]:
a.dtype

dtype('<M8[D]')

In [ ]:
a.astype('int64')

array([20404])