## NUMPY ( numerical Python)

## 1. Create array

In [1]:
l1=[2,3,5]
l2=[5,6,9]

In [2]:
import numpy as np

In [3]:
a1=np.array(l1)
a2=np.array(l2)

In [4]:
a1-a2

array([-3, -3, -4])

In [5]:
## 1D array
a1=np.array([4,5,6,7,9])

In [6]:
a1

array([4, 5, 6, 7, 9])

In [7]:
## 2d 
a2=np.array([[3,4,5],[6,7,8]])
a2
## 3d 

array([[3, 4, 5],
       [6, 7, 8]])

In [8]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.array(list(range(0,50,5)))

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [19]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [20]:
np.random.rand(20)

array([0.75215602, 0.0919353 , 0.99855592, 0.49942828, 0.8246776 ,
       0.28713994, 0.64172669, 0.9154326 , 0.50646965, 0.84647256,
       0.93367579, 0.98976377, 0.22788648, 0.42673809, 0.14585934,
       0.4738119 , 0.92960168, 0.57384058, 0.47578818, 0.71780089])

In [21]:
np.random.seed(42)
np.random.randint(0,10,50)

array([6, 3, 7, 4, 6, 9, 2, 6, 7, 4, 3, 7, 7, 2, 5, 4, 1, 7, 5, 1, 4, 0,
       9, 5, 8, 0, 9, 2, 6, 3, 8, 2, 4, 2, 6, 4, 8, 6, 1, 3, 8, 1, 9, 8,
       9, 4, 1, 3, 6, 7], dtype=int32)

In [22]:
np.random.seed(42)
np.random.randint(0,50,100)

array([38, 28, 14, 42,  7, 20, 38, 18, 22, 10, 10, 23, 35, 39, 23,  2, 21,
        1, 23, 43, 29, 37,  1, 20, 32, 11, 21, 43, 24, 48, 26, 41, 27, 15,
       14, 46, 43,  2, 36,  6, 20,  8, 38, 17,  3, 24, 13, 49,  8, 25,  1,
       19, 27, 46,  6, 43,  7, 46, 34, 13, 16, 35, 49, 39,  3,  1,  5, 41,
        3, 28, 17, 25, 43, 33,  9, 35, 13, 30, 47, 14,  7, 13, 22, 39, 20,
       15, 44, 17, 46, 23, 25, 24, 44, 40, 28, 14, 44,  0, 24,  6],
      dtype=int32)

### 2. Array attributes

In [23]:
a=np.array([3,4,5])

In [24]:
a.dtype

dtype('int64')

In [25]:
a=a.astype('int32')

In [26]:
a.dtype

dtype('int32')

In [27]:
b=np.array([1,2,'a'])

In [28]:
b.dtype

dtype('<U21')

In [29]:
a.ndim

1

In [30]:
c=np.array([[[2,3,4],[5,6,8]],[[8,2,3],[5,6,7]]])

In [31]:
c.ndim

3

In [32]:
c.shape

(2, 2, 3)

In [33]:
c.size

12

In [34]:
b.shape

(3,)

In [35]:
c.shape

(2, 2, 3)

In [36]:
a.size

3

In [37]:
b.size

3

In [38]:
c.size

12

In [39]:
e=np.array(['a','b','c','d','e'])

In [40]:
m,n=np.unique(e,return_index=True)

In [41]:
m

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [42]:
n

array([0, 1, 2, 3, 4])

### 3. Array operations

In [43]:
x=np.array([4,5,6])

In [44]:
## 1. arithemetic ops
x+2

array([6, 7, 8])

In [45]:
x-2

array([2, 3, 4])

In [46]:
x*3

array([12, 15, 18])

In [47]:
## 2.function ops
np.sum(x)

np.int64(15)

In [48]:
np.mean(x)

np.float64(5.0)

In [49]:
z=np.array([3,4,5])

In [50]:
z.ndim

1

In [51]:
y=np.array([[2],[3],[5]])

In [52]:
y.ndim

2

In [53]:
np.median(a)

np.float64(4.0)

In [54]:
from scipy import stats

In [55]:
stats.mode(a)

ModeResult(mode=np.int32(3), count=np.int64(1))

In [56]:
a.mean()

np.float64(4.0)

In [57]:
np.mean(a)

np.float64(4.0)

In [58]:
np.std(a)

np.float64(0.816496580927726)

In [59]:
a.std()

np.float64(0.816496580927726)

In [60]:
np.var(a)

np.float64(0.6666666666666666)

In [61]:
a.var()

np.float64(0.6666666666666666)

In [62]:
## column wise and row wise operations
m=np.array([[2,3,4],[5,6,7],[7,8,4]])

In [63]:
m

array([[2, 3, 4],
       [5, 6, 7],
       [7, 8, 4]])

In [64]:
## columns wise
## axis=0 (columns)
## axis=1 (rows)

In [65]:
m.sum(axis=0)

array([14, 17, 15])

In [66]:
m.sum(axis=1)

array([ 9, 18, 19])

In [67]:
## array broadcasting
m=np.array([[2,3,4],[5,6,7],[7,8,4]])

In [68]:
m.ndim

2

In [69]:
n=np.array([3,5,6])

In [70]:
n.ndim

1

In [71]:
m

array([[2, 3, 4],
       [5, 6, 7],
       [7, 8, 4]])

In [72]:
m+n

array([[ 5,  8, 10],
       [ 8, 11, 13],
       [10, 13, 10]])

In [73]:
m

array([[2, 3, 4],
       [5, 6, 7],
       [7, 8, 4]])

In [74]:
w=np.array([[1,2,3],[6,7,8],[9,0,5]])

In [75]:
w

array([[1, 2, 3],
       [6, 7, 8],
       [9, 0, 5]])

In [76]:
m.dot(w)

array([[ 56,  25,  50],
       [104,  52,  98],
       [ 91,  70, 105]])

In [77]:
np.dot(m,w)

array([[ 56,  25,  50],
       [104,  52,  98],
       [ 91,  70, 105]])

In [78]:
m@w

array([[ 56,  25,  50],
       [104,  52,  98],
       [ 91,  70, 105]])

In [79]:
np.cross(m,w)

array([[  1,  -2,   1],
       [ -1,   2,  -1],
       [ 40,   1, -72]])

In [80]:
np.linalg.inv(m)

array([[-2.13333333,  1.33333333, -0.2       ],
       [ 1.93333333, -1.33333333,  0.4       ],
       [-0.13333333,  0.33333333, -0.2       ]])

## 4.NumPy Copy vs View, Shape Manipulation, and Reshaping Arrays

In [81]:
l=[2,3,4,5,6,7]

In [82]:
x=l[2:5]

In [83]:
l

[2, 3, 4, 5, 6, 7]

In [84]:
x

[4, 5, 6]

In [85]:
l[3]=45

In [86]:
x

[4, 5, 6]

In [87]:
l

[2, 3, 4, 45, 6, 7]

In [88]:
l

[2, 3, 4, 45, 6, 7]

In [89]:
x=l.copy()

In [90]:
l

[2, 3, 4, 45, 6, 7]

In [91]:
x

[2, 3, 4, 45, 6, 7]

In [92]:
x[3]=60

In [93]:
x

[2, 3, 4, 60, 6, 7]

In [94]:
l

[2, 3, 4, 45, 6, 7]

In [95]:
z=np.arange(1,13)

In [96]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [97]:
z.reshape(3,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 5.NumPy Array Iteration, Joining, and Splitting

In [98]:
a1=np.array([1,2,3,5])
a2=np.array([[2,3,4],[5,6,7],[9,8,1]])
a3=np.array([[[1,2,3],[5,6,7],[6,7,7]]])

In [99]:
a3.ndim

3

In [100]:
for i in a1:
    print(i,end=" ")

1 2 3 5 

In [101]:
a2

array([[2, 3, 4],
       [5, 6, 7],
       [9, 8, 1]])

In [102]:
for i in a2:
    for j in i:
        print(j,end=" ")

2 3 4 5 6 7 9 8 1 

In [103]:
for i in a3:
    for j in i:
        for k in j:
            print(k,end=" ")

1 2 3 5 6 7 6 7 7 

In [104]:
for i in np.nditer(a3):
    print(i,end=" ")

1 2 3 5 6 7 6 7 7 

### 6. NumPy Searching, Sorting, and Filtering

In [105]:
a1=np.array([3,4,2,1,7])

In [131]:
## searching
indices=np.where(a1>2)

In [132]:
indices

(array([0, 1, 4]),)

In [137]:
np.extract(a1>2,a1)

array([3, 4, 7])

In [133]:
b=np.array([10,3,5,90,56,23])

In [134]:
## sorting
np.sort(b)

array([ 3,  5, 10, 23, 56, 90])

In [110]:
b.sort()

In [111]:
b

array([ 3,  5, 10, 23, 56, 90])

In [112]:
c=np.array([5,34,21,9,4])

In [113]:
c

array([ 5, 34, 21,  9,  4])

In [114]:
np.extract(c>10,c)

array([34, 21])

In [138]:
l1=np.array([5,6,7])
l2=np.array([4,3,2])
l3=np.array([9,0,3])

In [139]:
np.stack((l1,l2,l3))

array([[5, 6, 7],
       [4, 3, 2],
       [9, 0, 3]])

In [140]:
x1=np.hstack((l1,l2,l3))

In [141]:
x1

array([5, 6, 7, 4, 3, 2, 9, 0, 3])

In [142]:
x2=np.vstack((l1,l2,l3))  ## np.stack=np.vstack

In [143]:
x2

array([[5, 6, 7],
       [4, 3, 2],
       [9, 0, 3]])

In [144]:
x3=np.dstack((l1,l2,l3))

In [145]:
x3

array([[[5, 4, 9],
        [6, 3, 0],
        [7, 2, 3]]])

In [120]:
print(x1)
print(x2)
print(x3)

[5 6 7 4 3 2 9 0 3]
[[5 6 7]
 [4 3 2]
 [9 0 3]]
[[[5 4 9]
  [6 3 0]
  [7 2 3]]]


In [121]:
np.split(x1,3)

[array([5, 6, 7]), array([4, 3, 2]), array([9, 0, 3])]

In [122]:
np.vsplit(x2,3)

[array([[5, 6, 7]]), array([[4, 3, 2]]), array([[9, 0, 3]])]

In [123]:
np.hsplit(x1,3)  ## np.split=np.hsplit

[array([5, 6, 7]), array([4, 3, 2]), array([9, 0, 3])]

In [124]:
np.dsplit(x3,3)

[array([[[5],
         [6],
         [7]]]),
 array([[[4],
         [3],
         [2]]]),
 array([[[9],
         [0],
         [3]]])]

In [148]:
import numpy as np
from datetime import datetime

In [149]:
order_date = np.array([
    datetime(2020,3,12),
    datetime(2021,4,13),
    datetime(2022,5,15),
    datetime(2023,6,18),
    datetime(2025,9,23)
])

In [150]:
order_date

array([datetime.datetime(2020, 3, 12, 0, 0),
       datetime.datetime(2021, 4, 13, 0, 0),
       datetime.datetime(2022, 5, 15, 0, 0),
       datetime.datetime(2023, 6, 18, 0, 0),
       datetime.datetime(2025, 9, 23, 0, 0)], dtype=object)

In [152]:
order_date.dtype

dtype('O')

In [129]:
a.dtype

dtype('<M8[D]')

In [130]:
a.astype('int64')

array([20404])