## Numpy

In [1]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Python314\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

## 1. Array Create

In [3]:
## 1d array
a=np.array([3,4,8,9])

In [4]:
a

array([3, 4, 8, 9])

In [5]:
## 2d array
b=np.array([[3,4,6,7,8],[5,6,9,8,2]])

In [6]:
b

array([[3, 4, 6, 7, 8],
       [5, 6, 9, 8, 2]])

In [7]:
c=np.array([[[3,4,5],[2,3,9],[4,5,2]]])

In [8]:
c

array([[[3, 4, 5],
        [2, 3, 9],
        [4, 5, 2]]])

In [9]:
d=np.zeros(5)

In [10]:
d

array([0., 0., 0., 0., 0.])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
list(range(2,10,2))

[2, 4, 6, 8]

In [15]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.linspace(0,1,5)  ## np.linspace(start,end,partition_value)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.random.rand(3)

array([0.82494358, 0.27661213, 0.73283601])

In [20]:
np.random.seed(42)
a=np.random.rand(10)

In [21]:
a

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [71]:
from datetime import date

In [87]:
y=np.array([np.datetime64(date(2020,6,4)),np.datetime64(date(2019,12,11))])

In [88]:
y

array(['2020-06-04', '2019-12-11'], dtype='datetime64[D]')

In [92]:
y=y.astype('int64')

In [93]:
y

array([18417, 18241])

In [ ]:
## 2. Array Attributes

In [ ]:
a=np.array([2,4,5,6,9])


In [79]:
a.dtype

dtype('int16')

In [78]:
a=a.astype('int16')

In [23]:
## dimension
a.ndim

1

In [24]:
b=np.array([[3,4,5],[5,6,9]])

In [25]:
b.ndim

2

In [26]:
## shape
a.shape

(5,)

In [27]:
b.shape

(2, 3)

In [56]:
a

array([2, 4, 5, 6, 9])

In [57]:
## data_types
a.dtype

dtype('int64')

In [58]:
z=a.astype('float')

In [60]:
z.dtype

dtype('float64')

In [61]:
x=np.array(['a','b','c','d','e'])

In [62]:
x

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [63]:
m,n=np.unique(x,return_index=True)

In [64]:
m

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [65]:
n

array([0, 1, 2, 3, 4])

In [44]:
b.dtype

dtype('int64')

In [30]:
## size
a.size

5

In [31]:
b.size

6

In [32]:
c=np.array([2,4,"hello",5])

In [33]:
c.dtype

dtype('<U21')

## 3. Array operations
### 3.1 arithmetic

In [34]:
a

array([2, 4, 5, 6, 9])

In [35]:
a+3

array([ 5,  7,  8,  9, 12])

In [36]:
a*3

array([ 6, 12, 15, 18, 27])

### 3.2 functions based

In [37]:
a

array([2, 4, 5, 6, 9])

In [38]:
b=np.sum(a)

In [39]:
np.mean(a)

np.float64(5.2)

In [40]:
np.max(a)

np.int64(9)

In [41]:
np.min(a)

np.int64(2)